sudo: false
addons:
  sauce_connect:
    no_ssl_bump_domains: "all" # Needed for WebSockets to work
  hosts:
    - testinghost.com # Route to 127.0.0.1 so Sauce tests work
branches:
  only:
    - master
    - /^v.*$/ # Tagged builds (Travis branch name = tag name)

jobs:
  include:
    - stage: Test and Deploy
      language: node_js
      node_js: "14" # Must build in Node 8+ (for webpack and babel-loader)
      script:
        # Ensure that you can build in Node 8+ and tests pass in Node 6+

        - nvm use 14
        - npm run build # test-src, build, test-build-node

        - nvm install 12
        - nvm use 12
        - npm run build # test-src, build, test-build-node
        
        - nvm install 10
        - nvm use 10
        - npm run build # test-src, build, test-build-node
        
        - nvm install 8
        - nvm use 8
        - npm run build # test-src, build, test-build-node

        - npm run test-build-browsers # Browser tests only once on 8+ for transilation

        - nvm install 6
        - nvm use 6
        - npm run test-build-node
        
        - npm run coveralls
      deploy: # Can't use npm provider because you need to publish the build folder
        provider: script
        skip_cleanup: true # Preserve the build so it can be published
        script:
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >>
          $HOME/.npmrc && npm publish build
        on:
          tags: true # Only deploy to NPM on tagged commits (new versions)
